import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import { cn } from "./lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Awwwards Rebuild - O'Shane Howard Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          // "w-screen",
          // "h-screen",
          "overflow-hidden",
          "bg-[#ebdc0b]"
        )}
      >
        {children}
      </body>
    </html>
  );
}
